CustomerPortal/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CustomerPortal.Models;
using Ninject;
using SAP.Entities;

namespace CustomerPortal.Controllers
{
    public class InvoiceController : _ApplicationController
    {
        [Inject]
        public IRepository<Invoice, SAPDatabaseContext> invoiceRepo { get; set; }


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadInvoices(DataTableParamModel param)
        {
            var allInvoices = invoiceRepo.GetGroup(x => x.CustomerNumber == "LY02");
            IEnumerable<Invoice> filteredInvoices;

            if (!string.IsNullOrEmpty(param.sSearch))
            {
                filteredInvoices = allInvoices.AsEnumerable()
                         .Where(x => x.InvoiceNumber.Contains(param.sSearch) ||
                         x.PONumber.Contains(param.sSearch) ||
                         x.Status.Contains(param.sSearch) ||
                         x.InvoiceDate.ToString().Contains(param.sSearch) ||
                         x.InvoiceAmount.ToString().Contains(param.sSearch));
            }
            else
            {
                filteredInvoices = allInvoices;
            }

            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);

            Func<Invoice, string> orderingFunction =
                (x => sortColumnIndex == 0 ? x.InvoiceNumber :
                sortColumnIndex == 1 ? x.PONumber :
                sortColumnIndex == 2 ? x.Status :
                sortColumnIndex == 3 ? x.InvoiceDateSAP : x.InvoiceAmount.ToString());

            var sortDirection = Request["sSortDir_0"]; // asc or desc
            if (sortDirection == "asc")
                filteredInvoices = filteredInvoices.OrderBy(orderingFunction);
            else
                filteredInvoices = filteredInvoices.OrderByDescending(orderingFunction);

            var displayedInvoices = filteredInvoices
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength);

            var result = Mapper.Map<IEnumerable<InvoiceListItemViewModel>>(displayedInvoices);

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = allInvoices.Count(),
                iTotalDisplayRecords = filteredInvoices.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

CustomerPortal/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CustomerPortal.Models;
using Ninject;
using SAP.Entities;

namespace CustomerPortal.Controllers
{
    public class OrderController : _ApplicationController
    {
        [Inject]
        public IRepository<Order, SAPDatabaseContext> orderRepo { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadOrders(DataTableParamModel param)
        {
            var allOrders = orderRepo.GetGroup(x => x.SoldTo == "LY02");
            IEnumerable<Order> filteredOrders;

            if (!string.IsNullOrEmpty(param.sSearch))
            {
                string searchTerm = param.sSearch.ToLower();
                filteredOrders = allOrders.AsEnumerable()
                         .Where(x => x.SalesOrder.Contains(searchTerm) ||
                         x.PurchaseOrder.ToLower().Contains(searchTerm) ||
                         x.ShipName.ToLower().Contains(searchTerm) ||
                         x.Status.ToLower().Contains(searchTerm) ||
                         x.OrderDate.ToString().Contains(searchTerm) ||
                         x.OrderValue.ToString().Contains(searchTerm));
            }
            else
            {
                filteredOrders = allOrders;
            }

            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);

            Func<Order, string> orderingFunction =
                (x => sortColumnIndex == 0 ? x.SalesOrder :
                sortColumnIndex == 1 ? x.PurchaseOrder :
                sortColumnIndex == 2 ? x.ShipName :
                sortColumnIndex == 3 ? x.StatusCode :
                sortColumnIndex == 4 ? x.OrderDateSAP : x.OrderValue.ToString());

            var sortDirection = Request["sSortDir_0"]; // asc or desc
            if (sortDirection == "asc")
                filteredOrders = filteredOrders.OrderBy(orderingFunction);
            else
                filteredOrders = filteredOrders.OrderByDescending(orderingFunction);

            var displayedOrders = filteredOrders
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength);

            var result = Mapper.Map<IEnumerable<OrderListItemViewModel>>(displayedOrders);

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = allOrders.Count(),
                iTotalDisplayRecords = filteredOrders.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

CustomerPortal/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using CustomerPortal.Entities;
using CustomerPortal.Models;
using Ninject;
using SAP.Entities;

namespace CustomerPortal.Controllers
{
    public class ProductController : _ApplicationController
    {
        [Inject]
        public IRepository<Product, CustomerPortalDatabaseContext> productRepo { get; set; }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult LoadProducts(DataTableParamModel param)
        {
            var allProducts = productRepo.GetGroup(x => x.CustomerNumber == "LY02");
            IEnumerable<Product> filteredProducts;

            if (!string.IsNullOrEmpty(param.sSearch))
            {
                filteredProducts = allProducts
                         .Where(x => x.Name.Contains(param.sSearch) ||
                         x.SKU.Contains(param.sSearch) ||
                         x.CustomerSKU.Contains(param.sSearch) ||
                         x.Description.Contains(param.sSearch));
            }
            else
            {
                filteredProducts = allProducts;
            }

            var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);

            Func<Product, string> orderingFunction = 
                (x => sortColumnIndex == 1 ? x.SKU :
                sortColumnIndex == 2 ? x.CustomerSKU :
                sortColumnIndex == 3 ? x.Description :
                sortColumnIndex == 4 ? x.Size : x.Price.ToString());

            var sortDirection = Request["sSortDir_0"]; // asc or desc
            if (sortDirection == "asc")
                filteredProducts = filteredProducts.OrderBy(orderingFunction);
            else
                filteredProducts = filteredProducts.OrderByDescending(orderingFunction);

            var displayedProducts = filteredProducts
                .Skip(param.iDisplayStart)
                .Take(param.iDisplayLength);

            var result = Mapper.Map<List<ProductListItemViewModel>>(displayedProducts);

            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = allProducts.Count(),
                iTotalDisplayRecords = filteredProducts.Count(),
                aaData = result
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

CustomerPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WCPG Customer Portal</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="./" class="navbar-brand"><img src="~/Content/Images/logo.png" height="35" width="35"> Customer Portal</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                    <li>@Html.ActionLink("Invoices", "Index", "Invoice")</li>
                    <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    <li>@Html.ActionLink("Resources", "Index", "Home")</li>
                    <li>@Html.ActionLink("Users", "Index", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - West Chester Protective Gear</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

CustomerPortal/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WCPG Customer Portal</title>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>